//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoFotos.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class backup_images_project
    {
        public string id_core { get; set; }
        public string id_image { get; set; }
        public string project { get; set; }
        public string container { get; set; }
        public string ruta_cod { get; set; }
        public string filename { get; set; }
        public string link_azure { get; set; }
        public string name { get; set; }
        public string origen { get; set; }
    }
}
