//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoFotos.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MardisEngine_TestEntities : DbContext
    {
        public MardisEngine_TestEntities()
            : base("name=MardisEngine_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<backup_images_project> backup_images_project { get; set; }
        public virtual DbSet<DatosMigracionAzure> DatosMigracionAzure { get; set; }
        public virtual DbSet<vw_fotos_mardisp> vw_fotos_mardisp { get; set; }
    
        public virtual ObjectResult<sp_Config_Parameters_Images_Azure_Result> sp_Config_Parameters_Images_Azure(string uri, string key)
        {
            var uriParameter = uri != null ?
                new ObjectParameter("uri", uri) :
                new ObjectParameter("uri", typeof(string));
    
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Config_Parameters_Images_Azure_Result>("sp_Config_Parameters_Images_Azure", uriParameter, keyParameter);
        }
    
        public virtual ObjectResult<Traerimagen_Result> Traerimagen(string id_core, string container)
        {
            var id_coreParameter = id_core != null ?
                new ObjectParameter("id_core", id_core) :
                new ObjectParameter("id_core", typeof(string));
    
            var containerParameter = container != null ?
                new ObjectParameter("container", container) :
                new ObjectParameter("container", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Traerimagen_Result>("Traerimagen", id_coreParameter, containerParameter);
        }
    }
}
