//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoFotos.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_fotos_mardisp
    {
        public string Code { get; set; }
        public string Title { get; set; }
        public string key { get; set; }
        public string id { get; set; }
        public string idimg { get; set; }
        public byte[] value { get; set; }
    }
}
